### ISSUE TITLE
ComfyChair Conference Management System

### ISSUE THREAD

**Issue by GabrielEValenzuela** [GabrielEValenzuela/ComfyChairCpp#1]
# Project Charter

## Project Title
ComfyChair - A Comprehensive System for Managing Scientific Conferences

## Project Start Date
2024-07-15

## Project End Date
2025-07-27

## Project Managers
Martín Venturino
Gabriel Valenzuela

## Objectives
The objective of ComfyChair is to create a robust digital platform for organizing and managing scientific conferences. This system will streamline the submission, review, and management of conference papers and sessions, enhancing the overall efficiency and accessibility of conference proceedings.

## Scope
- **Development of a user registration module** for chairs, reviewers, and authors with role management.
- **Creation of sessions and tracks** with specific themes like Software Engineering, AI, and Big Data.
- **Handling of paper submissions** with specific criteria for regular papers and posters.
- **Implementation of the review process**, including bidding, assignment, and selection phases.
- **User interface design** that is intuitive and user-friendly for all roles.
- **Reporting features** for conference analytics and feedback.

## Out of Scope
- Mobile application development.
- Integration with third-party payment gateways for conference fees.
- Real-time collaboration tools for live editing of submissions.

## Deliverables
1. **System Requirements Specification** - A detailed document outlining all technical and functional requirements of the ComfyChair system.
2. **System Design Document** - Architectural diagrams and design specifications.
3. **Implemented System** - Fully functional software ready for deployment.

## Stakeholders
- **Chairs**: Conference organizers who oversee the creation and management of sessions.
- **Reviewers**: Individuals responsible for reviewing submissions.
- **Authors**: Researchers and professionals submitting their work for review.
- **Conference Attendees**: Indirect beneficiaries of the system’s efficiency.

## Risks
- Delays in development due to unforeseen technical challenges.
- Difficulty in user adoption due to resistance to new technology.
- Security risks associated with data breaches or unauthorized access.

## Assumptions
- Stakeholders are cooperative and provide timely feedback.
- Regular updates and maintenance are planned post-deployment.
- Highly knowledge of the problem domain.

## Approval
 ✅

**Comment by marventu94** [comment]
LGTM
