### ISSUE TITLE
System design 

### ISSUE THREAD

**Issue by GabrielEValenzuela** [GabrielEValenzuela/ComfyChairCpp#5]
# Software Design Document for ComfyChair Conference Management System

## 1. Introduction

This document provides a detailed architectural outline for the ComfyChair system, focusing on the Conference Manager component. The system is designed to manage the lifecycle of tracks and articles within a conference.

## 2. System Overview

The ComfyChair system facilitates the management of scientific conferences, handling multiple tracks and the associated articles. The Conference Manager is responsible for controlling the state transitions of these tracks and ensuring that all tracks within a conference move synchronously through their respective states.

## 3. Design Considerations

- **State Synchronization**: All tracks within a conference must be synchronized in terms of state transitions to maintain uniformity across the conference.
- **Article Submission Deadline**: The submission of articles is tightly coupled with the track's state, ending precisely when the bidding phase begins.
- **Notification Responsibility**: The first author listed for each article is designated as the primary contact for notifications related to that article.

## 4. Class Diagram

![TyH-final](https://github.com/user-attachments/assets/f662c910-f0fe-43a7-a4d3-2ab6b947eafa)

## 5. Conclusion

The design of the ComfyChair Conference Management System is aimed at providing robust management of conference tracks and efficient handling of scholarly articles with a focus on synchronization and clear responsibility demarcation.

**Comment by GabrielEValenzuela** [comment]
Idea 1:

```mermaid

---
title: ComfyChairC++
---
classDiagram
    
    Conference "1" --> "*" Track
    Conference "1" --> "*" User
    Track "1" --> "*" Article
    Article <|-- ArticlePoster
    Article <|-- ArticleRegular
    trackEnum <..Track

    class Conference{
        m_organizers : std::vector<std::string>
        m_autors : std::vector<std::string>
        m_tracks : std::vector<Track>
        
    }

    class User{
        m_fullName : std::string
        m_afilation : std::string
        m_email : std::string
        m_password : std::string
        m_handleNotification : bool
    }

    class Article{
        m_articleTitle : std::string
        m_autors : std::vector< User >
        m_attachedFile : std::string
        virtual bool isValid()
    }

    class ArticlePoster{
        m_secondAttachedFile : std::string
    }

    class ArticleRegular{
        m_abstract : std::string
        bool isValid() override
    }

    class trackEnum{
        <<Enumeration>>
        TRACK_STATUS::RECEPTION
        TRACK_STATUS::BIDDING
        TRACK_STATUS::REVISION
    }

    note for trackEnum "Only receive articles in reception."

    class Track{
        - m_trackTopic : std::string
        - m_currentState : trackEnum
        - m_deadline : std::chrono
        - m_articles : std::vector< Article >
        - m_reviewers : std::vector<std::string>
        void setState(newState: trackEnum)
        trackEnum getState()
        void addArticle(Article)
        void modifyArticle(Article)
    }

```

**Comment by marventu94** [comment]
Idea 2: caso completo aunque no me gusta que hay varias clases que tiene responsabilidad mezclada

```mermaid

---
title: ComfyChairC++
---
classDiagram
    
    Conference "1" --> "*" Track
    Conference "1" --> "*" User
    Track "1" --> "*" Article
    Article <|-- ArticlePoster
    Article <|-- ArticleRegular
    trackEnum <..Track

    UserReviewer <|-- User
    UserReviewer "1" --> "*" Bid
    bidEnum <.. Bid
    UserReviewer "1" --> "*" Review

    SelectionTypeStategy "1" <-- "1" Track

    SelectionTypeStategy <.. selectionTypeStategyBest
    SelectionTypeStategy <.. selectionTypeStategyFixedCut

    class Conference{
        m_organizers : std::vector<std::string>
        m_autors : std::vector<std::string>
        m_tracks : std::vector<Track>
        
    }

    class User{
        m_fullName : std::string
        m_afilation : std::string
        m_email : std::string
        m_password : std::string
        m_handleNotification : bool
    }

    class UserReviewer {
        m_bids: vector<Bid>
        m_reviews: vector<Review>

        void addBid(Bid)
        void modifyBid(Bid)
    }

    class Bid {
        m_article: Article
        m_bid: bidEnum
    }

    class bidEnum{
        <<Enumeration>>
        BID_STATUS::INTERESTED
        BID_STATUS::NO_INTERESTED
        BID_STATUS::MAYBE
    }

    class Review {
        m_article: Article,
        m_text: std::String,
        m_point: std::Integer, 
    }

    note for Review "Point has to be between -3 to +3"

    note for Article "Firts author recive notification."

    class Article{
        m_articleTitle : std::string
        m_autors : std::vector< User >
        m_attachedFile : std::string
        virtual bool isValid()
    }

    class ArticlePoster{
        m_secondAttachedFile : std::string
    }

    class ArticleRegular{
        m_abstract : std::string
        bool isValid() override
    }

    class trackEnum {
        <<Enumeration>>
        TRACK_STATUS::RECEPTION
        TRACK_STATUS::BIDDING
        TRACK_STATUS::REVISION
        TRACK_STATUS::SELECTION
    }

    note for trackEnum "Only receive articles in reception and before deadline."

    note for Track "se supone que de la seleccion sale una conferencia o cuando se crea una ???"

    class Track{
        - m_trackTopic : std::string
        - m_currentState : trackEnum
        - m_deadline : std::chrono
        - m_articles : std::vector<Article>
        - m_reviewers : std::vector<UserReviewer>
        void setState(newState: trackEnum)
        trackEnum getState()

        void addArticle(Article)
        void modifyArticle(Article)

        void addReviewer(UserReviewer)

        void revision()

        void selection()
        void changeSelectionTypeStrategy(SelectionTypeStategy)
        - m_selection_type_strategy: SelectionTypeStategy
    }

    class SelectionTypeStategy {
        void execute()
    }

    class selectionTypeStategyFixedCut {
        void execute()
    }

    class selectionTypeStategyBest {
        void execute()
    }

```

**Comment by GabrielEValenzuela** [comment]
# Idea 3

- I think we can use this approach, delegating the time management to the `ConferenceManager` object, and integrating the different types of tracks. 
- This could be improved to include a better code.

```mermaid

---
title: ComfyChairC++
---
classDiagram
    
    Conference "1" --o "*" Track
    Conference "1" --o "*" TrackI
    Conference "1" --o "*" User
    ConfereManager --* Conference
    ConfereManager --> NotificationSystem
    NotificationSystem --* Observer
    Track "1" --o "*" Article
    Article <|-- ArticlePoster
    Article <|-- ArticleRegular
    trackStatus <--Track
    articleWeight <-- Article

    TrackI <|-- TrackRegular
    TrackI <|-- TrackWorkshop
    TrackI <|-- TrackPoster

    class Conference{
        m_organizers : std::vector< User >
        m_autors : std::vector< User >
        m_tracks : std::vector<Track>
        m_biddingStart : std::chrono::time_point
        m_revisionStart : std::chrono::time_point
        m_selectionStart : std::chrono::time_point
    }

    note for Conference "m_biddingStart mark the start of bidding.\n m_revisionStart mark the start of revision and end of bidding.\n m_selectionStart mark the start of the selection and end of revision."

    class ConfereManager{
        - m_confere : Conference
        void starBidding()
        void starRevision()
        void starSelection()
    }

    class NotificationSystem {
        +attach(observer)
        +detach(observer)
        +notify()
    }
    class Observer {
        +update()
    }

    class User{
        m_fullName : std::string
        m_afilation : std::string
        m_email : std::string
        m_password : std::string
        m_handleNotification : bool
    }

    class Article{
        m_articleTitle : std::string
        m_autors : std::vector< User >
        m_attachedFile : std::string
        m_articleWeight : articleWeight
        virtual bool isValid()
    }

    class ArticlePoster{
        m_secondAttachedFile : std::string
    }

    class ArticleRegular{
        m_abstract : std::string
        bool isValid() override
    }

    class trackStatus{
        <<Enumeration>>
        Reception
        Bidding
        Selection
    }

    class articleWeight{
        <<Enumeration>>
        Excellent
        VeryGood
        Good
        Neutral
        Bad
        VeryBad
        NotRecommended
    }

    note for trackStatus "Only receive articles in Reception."

    class TrackI{
        <<Interface>>
        void setState(newState: trackStatus)
        void addArticle(Article)
        void modifyArticle(Article)
    }

    class TrackRegular{

    }

    class TrackWorkshop{

    }

    class TrackPoster{

    }

    class Track{
        - m_trackTopic : std::string
        - m_currentState : trackStatus
        - m_deadline : std::chrono
        - m_articles : std::vector< Article >
        - m_reviewers : std::vector<std::string>
        - m_maxArticles : int
        void setState(newState: trackStatus)
        void addArticle(Article)
        void modifyArticle(Article)
    }

```

**Comment by marventu94** [comment]
Gabi, 

Gracias por pasar una nueva solución.  La estuvé mirando. No pudé tomar mucho lo de lo tuyo para mi siguiente iteración. La voy a dejar adjunta para que la puedas examinar.

Respecto a tu solución, me llamó la atención los siguentes puntos:
- Porque conference tiene estados? Los track eran los que pasaban de un estado a otros
- TrackStatus: faltaria el estado de asignación y revisión
- Article Weight: entiendo la idea pero no se si lo pondría dentro de Article. El recuento de puntos  de cada artículo se hace en la última etapa de selección  y solo se usa en ese mismo momento
- NotificationSystem creo que escapa de los requerimientos que nos pidieron, yo sacaría
- Me parece interesante la parte de las distintas clases de Track dependiendo el tipo. No seria del todo compatible con mi solución pero podemos ver de hacer un mezcla de las dos
- No agregaría las fecha con un chrono::time_point del bidding ni de revision porque ambas estados no tiene día de finalización. Queda a criterio del usuario cambiar los estados. El deadline solo afecta a la recepción

Adjunto mi solución:
![TyH](https://github.com/user-attachments/assets/72b3f97e-61f9-45d7-b207-7f7273737c03)
Consite en un patrón state para el tema de las distintas estados del Track implementando únicamente los métodos que se necesitan en cada caso y dejando el resto que tieren Exception. Según la documentación que estuvé leyendo esto es perfectamente válido. También la biblografía sugiere tener una referencia a la clase raíz (en este caso Track) para poder tener acceso a todos los atributos. 
Y por otro lado, se utiliza el patrón strategy para el tema de la selección de articulos, ya que en los requerimientos se aclara que  se deben poder cambiar o agregar más en un futuro.

Estamos en contacto

**Comment by GabrielEValenzuela** [comment]
Hola Tincho!

Me gusta ese state pattern para el track de la conferencia! Paso a responder las preguntas

> Porque conference tiene estados? Los track eran los que pasaban de un estado a otros

El objecto `ConferenceManager` setea los estados de los Tracks, o el stateTrack si unimos con tu diseño.

> TrackStatus: faltaria el estado de asignación y revisión

Revisión está y la asignación me parece que es consecuencia del esstado de bidding.

>Article Weight: entiendo la idea pero no se si lo pondría dentro de Article. El recuento de puntos de cada artículo se hace en la última etapa de selección y solo se usa en ese mismo momento

Agree, podemos generar de última un mapa Articulo <--> Puntaje

>NotificationSystem creo que escapa de los requerimientos que nos pidieron, yo sacaría

Esto sería el patrón observer, encargado de notificar a los encargados de revisión que comenzó dicha etapa.

>No agregaría las fecha con un chrono::time_point del bidding ni de revision porque ambas estados no tiene día de finalización. Queda a criterio del usuario cambiar los estados. El deadline solo afecta a la recepción.

Internamente podemos manejar los tiempos para marcar el paso de un estado a otro.

Veo de pulir el diseño hoy a la tarde para la meet de mañana!

**Comment by GabrielEValenzuela** [comment]
# Idea v4

## Class diagram


```mermaid

classDiagram

class User {
    -fullName: string
    -affiliation: string
    -email: string
    -password: string
    +performTasks(): void
}

class Chair {
    +performTasks(): void
}

class Reviewer {
    +performTasks(): void
}

class Author {
    +performTasks(): void
}

class RoleBehavior {
    +performRoleDuties(): void
}

class ChairBehavior {
    +performRoleDuties(): void
}

class ReviewerBehavior {
    +performRoleDuties(): void
}

class AuthorBehavior {
    +performRoleDuties(): void
}

class IArticle {
    <<Interface>>
    +isValid(): boolean
}

class ArticleRegular {
    -abstract: string
    +isValid(): boolean
}

class ArticlePoster {
    -secondAttachedFile: string
}

class articleWeight{
    <<Enumeration>>
    Excellent
    VeryGood
    Good
    Neutral
    Bad
    VeryBad
    NotRecommended
}

class ITrack {
    <<Interface>>
    +handleSubmissions(): void
}

class RegularTrack {
    +handleSubmissions(): void
}

class WorkshopTrack {
    +handleSubmissions(): void
}

class PosterTrack {
    +handleSubmissions(): void
}

class ITrackState {
    <<Interface>>
    +handleState(): void
    +stateName(): string
}

class ReceptionState {
    +handleState(): void
    +stateName(): string
}

class BiddingState {
    +handleState(): void
    +stateName(): string
}

class SelectionState {
    +handleState(): void
    +stateName(): string
}

class ISelectionStrategy {
    <<Interface>>
    +performSelection(): void
}

class CutSelectionStrategy {
    +performSelection(): void
}

class BestSelectionStrategy {
    +performSelection(): void
}

class Conference {
    -organizers: vector<User>
    -authors: vector<User>
    -tracks: vector<ITrack>
    -biddingStart: chrono::time_point
    -revisionStart: chrono::time_point
    -selectionStart: chrono::time_point
}

class ConferenceManager {
    -conference: Conference
    +startBidding(): void
    +startRevision(): void
    +startSelection(): void
}

class UserFactory {
    +createUser(type: string): User
}

class NotificationSystem {
    +attach(observer: Observer): void
    +detach(observer: Observer): void
    +notify(message: string): void
}

class Observer {
    +update(message: string): void
}

User <|-- Chair
User <|-- Reviewer
User <|-- Author
User "1" o-- "*" RoleBehavior : roles
Conference "1" o-- "*" ITrack
Conference "1" o-- "*" User
ConferenceManager "1" -- "1" Conference
ConferenceManager --> UserFactory
ITrack "1" --o "*" IArticle
ITrack --> ITrackState

ITrack <|-- RegularTrack
ITrack <|-- WorkshopTrack
ITrack <|-- PosterTrack

ITrack --> articleWeight

ITrackState <|-- ReceptionState
ITrackState <|-- BiddingState
ITrackState <|-- SelectionState
IArticle <|-- ArticleRegular
IArticle <|-- ArticlePoster
UserFactory --> User
NotificationSystem "1" -- "*" Observer : notifies
SelectionState --> ISelectionStrategy : strategy
ISelectionStrategy <|-- CutSelectionStrategy
ISelectionStrategy <|-- BestSelectionStrategy
User --|> Observer
RoleBehavior <|.. ChairBehavior
RoleBehavior <|.. ReviewerBehavior
RoleBehavior <|.. AuthorBehavior

```

## Justification

### Observer Pattern
**Usage**: The Observer pattern is utilized in the Notification System to manage updates related to article reviews and state changes effectively.

**Reason**: This pattern allows the system to maintain a subscription-like mechanism where objects (users) interested in certain events (like updates on article reviews) can listen and react to them without creating tight couplings between the subject (Notification System) and observers (Users). This decoupling allows the notification logic to be modified independently of the user objects, promoting flexibility and scalability.

### Factory Pattern
**Usage**: The Factory pattern is used through the `UserFactory` to instantiate different types of users (Chair, Reviewer, Author) based on the required role.

**Reason**: Employing the Factory pattern allows the system to encapsulate the instantiation logic for users, which makes the system easier to manage as it scales and evolves. This pattern supports the open/closed principle by enabling the introduction of new user types without modifying existing factory logic.

### Strategy Pattern
**Usage**: The Strategy pattern is applied within the `RoleBehavior` implementations for users, enabling dynamic changes in the user's role behavior at runtime.

**Reason**: This pattern provides the flexibility to assign different behaviors to objects (users) at runtime. For a user who may act both as a reviewer and an author, the Strategy pattern allows seamless switching or addition of responsibilities, enhancing the system's adaptability to varying conference roles.

### State Pattern
**Usage**: The State pattern is adopted in managing the state transitions of tracks (Reception, Bidding, and Selection states) through the `ITrackState` interface.

**Reason**: The State pattern facilitates state management within the tracks by encapsulating the state-specific behaviors within state objects. This approach reduces the complexity within the track objects themselves and provides a cleaner way to manage changes in the track's state over time, which is crucial for the dynamic environment of a conference lifecycle.

### Composite Pattern
**Usage**: Although not explicitly mentioned earlier, considering the hierarchical structure of conferences, tracks, and articles, the Composite pattern could be utilized to treat individual and composed objects uniformly.

**Reason**: This pattern would simplify the management of components (conferences, tracks, articles) by allowing the same operations to be applied both to parts (individual articles) and wholes (tracks or entire conferences), which can be particularly useful in operations like rendering views or calculating metrics.

**Comment by marventu94** [comment]
Gabi, interesante iteración. La estuvé analisando y vamos por buen camino.

Para ir adelantandonos a la reu de hoy, te quería dejar algunos comentarios:

* No faltaria dentro de ITrackState un estado para Asignación y Revisión

* ITrackState es como un patrón State con un Command, interesante propuesta. Lo que me cuesta ver es cómo va ser la implementación para adaptarse a cada caso. 
	Por ejemplo en 
	+ ReceptionState handleState debería permitirte agregar articulo o editar si ya estaba carga, como se adaptaría a esta situación.
	+ Cada state tiene entradas y salidas distintas. Como serian las distintas implementaciones para adaptarse a esto. No se si se puede sobrecargar un método de una interface en c++ ??
	+ Y que pasa en el caso del estado Selecction que se necesita hacer dos cosas. Hacer la seleccion y cambiar la estrategia de selección. Esto no se podría hacer si la interface probeé solo un método. Se podría llevar el método de cambio de estrategia de selección a la clase Track, ya que no hay restricciones de tiempo ni de estado para cambiar la forma que se seleccionan los artículos.

* ArticleWeight no deberia estar vinculado con los Rewiers

* No faltaría la clase Bid para motrar si un candidato a rewierer esta interesado, no interesado o quizas.

* Anidado con estos dos últimos puntos, los Rewiers no tendira que tener como atributos sus bids y los articulos que comentaron (el texto y el puntaje)

Desde ya muchas gracias Gabi
Estamos hablando. 
Saludos

**Comment by GabrielEValenzuela** [comment]
# JSON input

```json

{
  "conference": {
    "biddingStart": "2024-07-18T00:00:00Z",
    "revisionStart": "2024-07-18T00:00:00Z",
    "selectionStart": "2024-07-18T00:00:00Z",
    "users": [
      {
        "name": "John Doe",
        "email": "john.doe@example.com",
        "roles": ["Chair", "Reviewer"]
      },
      {
        "name": "Jane Smith",
        "email": "jane.smith@example.com",
        "roles": ["Author"]
      }
    ],
    "tracks": [
      {
        "trackType": "Regular",
        "trackTopic": "C++",
        "reviewers": ["John Doe"],
        "articles": [
          {
            "articleType": "Regular",
            "articleTitle": "Advanced C++ Techniques",
            "attachedFileUrl": "https://bit.ly/example",
            "abstract": "Detailed exploration of modern C++ features.",
            "authors": ["Jane Smith"]
          }
        ]
      },
      {
        "trackType": "Workshop",
        "trackTopic": "Data Science",
        "reviewers": ["John Doe"],
        "articles": [
          {
            "articleType": "Poster",
            "articleTitle": "Visualizing Big Data",
            "attachedFileUrl": "https://bit.ly/example",
            "additionalFileUrl": "https://bit.ly/example2",
            "authors": ["Jane Smith"]
          }
        ]
      },
     {
        "trackType": "Poster",
        "trackTopic": "Innovative Data Visualization Techniques",
        "reviewers": ["Alice Johnson"],
        "articles": [
          {
            "articleType": "Poster",
            "articleTitle": "Exploring Large Datasets with Interactive Posters",
            "attachedFileUrl": "https://bit.ly/interactivePoster",
            "additionalFileUrl": "https://bit.ly/posterSupplement",
            "abstract": "This poster demonstrates novel techniques for interacting with large datasets in a poster format, emphasizing user engagement and data accessibility.",
            "authors": ["Bob Smith"]
        }
    ]
  }


```

**Comment by marventu94** [comment]
![TyH-Final](https://github.com/user-attachments/assets/83137c89-7f67-42b0-9d3b-5df17e77dc75)


Consideraciones:
- El Conference Manager controla los estados de todos los tracks de una conferencia, manteniéndolos en el mismo estado y avanzando todos simultáneamente.
- Se asume que la fecha de inicio de un estado coincide con la finalización del estado anterior.
- La fecha límite para recibir artículos concluye en el momento en que comienza el bidding.
- Una vez creada la conferencia, se pueden empezar a enviar artículos.
- El primer autor del listado de autores de los artículos recibidos dentro del track es responsable de las notificaciones.

**Comment by GabrielEValenzuela** [comment]
LGTM!
