### ISSUE TITLE
RC 1 - Work Breakdown Structure for ComfyChair Conference Management System

### ISSUE THREAD

**Issue by GabrielEValenzuela** [GabrielEValenzuela/ComfyChairCpp#8]
# Description:
The purpose of this issue is to develop a comprehensive Work Breakdown Structure (WBS) for the ComfyChair conference management system. The WBS will outline all the tasks necessary to achieve the project goals, organized hierarchically to ensure clarity and manageability.

### Objectives:
- **Define Major Components**: Identify and outline the major components and functionalities of the ComfyChair system as top-level WBS elements.
- **Detailing Tasks**: Break down each major component into its constituent tasks, ensuring each task is manageable and measurable.
- **Assign Responsibilities**: Allocate responsibilities for each task to team members, ensuring clear accountability.
- **Estimate Timelines and Resources**: Provide preliminary estimates for time and resources required for each task, facilitating further project planning and resource allocation.

### Tasks to be Created:

1. #9 
   - Description: Develop and integrate functionalities to manage different types of articles, including submission, review, and archiving within the system.

2. #10
   - Description: Design and implement the logic to handle different states (e.g., Reception, Bidding, Review) of conference tracks, ensuring seamless transitions and synchronization across tracks.

3. #11
   - Description: Create the core logic for the Conference Manager to control and oversee the overall workflow of conferences, including track state synchronization and timeline management.

4. **Implement Bidding and Review Process Logic**
   - Description: Develop the mechanisms for handling the bidding and review processes, integrating user inputs and automated system decisions to manage paper evaluations effectively.

5. #13
   - Description: Implement a factory design pattern to dynamically create user objects with varying roles (Chair, Reviewer, Author) based on system requirements and user interactions.

6. **Establish End-to-End Testing Framework**
   - Description: Set up a comprehensive end-to-end testing framework to verify the complete functionality of the ComfyChair system, ensuring all components work harmoniously from start to finish.

**Comment by marventu94** [comment]
## Final Class Diagram

![TyH C++](https://github.com/user-attachments/assets/ac6cf9be-4441-4d5a-adb2-63ad519b1235)
